# ===================================
region = "ap-southeast-1"
instance_type = "t2.micro"
instance_name = "ec2_demo_instance_1"
key_pair_path = "./keypair/ec2_demo_key.pub"
key_pair_name = "ec2_demo_key_pair_1"
public_sg_name = "public_security_group_1"
public_sg_description = "public_security_group_dec_1"
private_sg_name = "private_security_group_1"
private_sg_description = "private_security_group_dec_1"